#!/bin/sh

# Must have xclip installed to even show menu.
xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ~/.scripts/emojis/emoji | dmenu -i -l 20 | sed "s/ .*//")

[ -n $chosen ] || exit

echo "$chosen" | tr -d '\n' | xclip -selection clipboard
notify-send "'$chosen' copied to clipboard." &
