#!/bin/bash

geolocation="$(curl --max-time 3 -s https://freegeoip.app/json/ | sed 's/,/\n/g; s/"//g' | awk -F: '/latitude/{print $2}; /longitude/{print $2}')"
lat=$(echo $geolocation | awk '{print $1}')
lon=$(echo $geolocation | awk '{print $2}')

url="https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=$lat&lon=$lon"

report="$(curl --max-time 3 -s "$url" | jq '.properties.timeseries[0].data | .instant.details.air_temperature, .next_1_hours')"
temp="$(echo "$report" | sed '1!d')"
precip="$(echo "$report" | awk '/precip/{print $2}' | sed 's/"//g')"
verbose="$(echo "$report" | awk '/symbol_code/{print $2}' | sed 's/"//g')"

icon=""  # ""

symbol="$(cat $HOME/.scripts/statusbar/weatheryr/icons.txt | fzf -f "$verbose" | sed '1!d; s/:.*$//g')"

[ -n "$symbol" ] && icon=$symbol

if [ -n "$temp" ] && [ -n "$precip" ]; then
    printf "%s%s%s%s" "$icon " "$temp°C " " $precip" "mm"
    printf " | "
fi
