#!/bin/bash

geolocation="$(curl -s https://freegeoip.app/json/ | sed 's/,/\n/g; s/"//g' | awk -F: '/latitude/{print $2}; /longitude/{print $2}')"
lat=$(echo $geolocation | awk '{print $1}')
lon=$(echo $geolocation | awk '{print $2}')

report="$(curl -s "https://api.met.no/weatherapi/locationforecast/1.9/?lat=$lat&lon=$lon" | awk '/\<\/temperature\>/; /\<\/precipitation\>/; /\<\/symbol\>/' | head -3 | sed 's/<\/\([^$]*\)$//g; s/"//g; s/<//; s/>//' | awk '/temp/{print $4}; /precip/{print $3}; /symbol/{print $2}' | sed 's/value\=//; s/id\=//')"

temp="$(echo $report | awk '{print $1}')"
precip="$(echo $report | awk '{print $2}')"
verbose="$(echo $report | awk '{print $3}')"

icon=""

symbol="$(awk -F: -v var=$verbose "{if (\$2 == var) {print \$1}}" $HOME/.scripts/statusbar/weatheryr/icons.txt)"

if [ "$(echo $symbol)" ]; then
    icon=$symbol
fi

printf "%s%s%s%s" "$icon " "$temp°C " " $precip" "mm"

printf " | "
