alias vim='vim --servername vim'
alias project='cd ~/Dropbox/ntnu/project'
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bashrc'
alias sa='sudo apt'
alias dfs='/usr/bin/git --git-dir=$HOME/.git-dotfiles/ --work-tree=$HOME'
alias starwars='telnet towel.blinkenlights.nl'
alias books='cd ~/Dropbox/books/'
alias filetypes='vim ~/.vim_runtime/vimrcs/filetypes.vim'
