alias vim='vim --servername vim'
alias project='cd ~/Dropbox/ntnu/project'
alias master='cd ~/Dropbox/ntnu/master'
alias vimrc='vim ~/.vimrc'
alias bashrc='vim ~/.bashrc'
alias sa='sudo apt'
alias dfs='/usr/bin/git --git-dir=$HOME/.git-dotfiles/ --work-tree=$HOME'
alias starwars='telnet towel.blinkenlights.nl'
alias books='cd ~/Dropbox/books/'
alias :q='exit'
alias rip='rm -rf'
alias spa='sudo pacman'
alias bctl='bluetoothctl'
