#!/bin/bash
# Give battery name as argument, e.g. 'BAT0'

capacity=$(cat /sys/class/power_supply/"$1"/capacity) || exit
status=$(cat /sys/class/power_supply/"$1"/status)

charging=""
notcharging=""
stagnantcharge="♻️"
charged="⚡"
lowbattery=""
bgimage=""

if [ "$capacity" -ge 90  ]; then
    capicon=""
    bgimage="battery100"
elif [ "$capacity" -ge 70  ]; then
    capicon=""
    bgimage="battery75"
elif [ "$capacity" -ge 50  ]; then
    capicon=""
    bgimage="battery50"
elif [ "$capacity" -ge 25  ]; then
    capicon=""
    bgimage="battery25"
else
    capicon=""
    warn="$lowbattery "
    bgimage="battery0"
fi

[ -z $warn  ] && warn=""

printf "%s%s%s%s" "$(echo "$status" | sed -e "s/,//;s/Discharging//;s/Not charging/$notcharging /;s/Charging/$charging /;s/Unknown/$stagnantcharge /;s/Full/$charged /;s/ 0*/ /g;s/ :/ /g")" "$warn" "$capicon  " "$(echo "$capacity" | sed -e 's/$/%/')"

printf " | "

if [ "$status" == "Charging" ]; then
    feh --no-fehbg --bg-fill "$HOME/.scripts/statusbar/battery/images/$bgimage-charging.png"
# else
#     feh --no-fehbg --bg-fill "$HOME/.scripts/statusbar/battery/images/$bgimage.png"
fi
