#!/bin/bash

codes=$HOME/.scripts/statusbar/weather/weathercodes.txt
symbols=$HOME/.scripts/statusbar/weather/weathersymbols.txt

report="$(curl -s wttr.in/?format=j1 | awk -F: '/temp_C/{print $2}; /weatherCode/{print $2;exit}' | sed 's/"//g; s/,//' | sed 's/^\s//')" || exit
temp="$(echo $report | awk '{print $1}')"
weathercode="$(echo $report | awk '{print $2}')"

icon=""

key="$(awk -F: "/$weathercode/{print \$2}" $codes)"
symbol="$(awk -F: "/$key/{print \$1}" $symbols)"

if [ "$(echo $symbol)" ]; then
    icon=$symbol
fi

printf "%s%s" "$icon " "$temp°C"

printf " | "
