#!/bin/bash

icons=""

[ "$(pgrep -i dropbox)" ] && dropbox-cli status | grep "Sync" > /dev/null && icons+="  累 "
[ "$(pgrep -i discord)" ] && icons+="ﭮ "
[ "$(pgrep -i steam)" ] && icons+=" "

[ -n "$icons" ] && for icon in $icons; do printf "$icon "; done && printf " | "
