#!/bin/bash

temp="$(sensors | awk -F: '/Tdie/{print $2;exit}; /Core/{print $2;exit}; /CPU/{print $2;exit}; /Tctl/{print $2;exit}' | awk '{print $1}')"
icon=""

printf "%s%s" "$icon" "$temp"

printf " | "
