#!/bin/bash

[[ "$(pacmd list-sinks | awk 'f{print;f=0} /\*/{f=1}')" == *"bluez"* ]] && printf " "

[[ "$(pacmd list-sources | awk 'f{print;f=0} /\*/{f=1}')" == *"Snowball"* ]] && printf " "

printf " | "
