#!/bin/bash

if [ $(playerctl -l | wc -l) -ge 1 ]; then
    player="$(playerctl -l | grep -i 'spotify')"
    
    if ! [ $(echo $player) ]; then
        for p in $(playerctl -l)
        do
            if [ "$(playerctl -p $p status)" != 'Stopped' ]; then
                player="$p"
                break
            fi
        done
    fi

    if [ "$(playerctl -p $player status)" = 'Playing' ]; then
        icon="  "
    elif [ "$(playerctl -p $player status)" = 'Paused' ]; then
        icon=" "
    else
        exit
    fi

    printf "$icon"

    MAXLENGTH=15

    artist="$(playerctl -p $player metadata artist)"
    title="$(playerctl -p $player metadata title)"
    if [ "$(echo $artist)" ] && [ "$(echo $title)" ]; then
        if [ $(printf "$title" | wc -c) -gt $MAXLENGTH ]; then
            title="$(printf "$title" | cut -c 1-$MAXLENGTH | sed 's/\W*$//').."
        fi
        trackinfo="$artist - $title"
        printf "$trackinfo"
    fi

    printf " | "
fi
