#!/bin/bash

volstat="$(amixer -D pulse get Master)"

[ "$(echo $volstat | grep "\[off\]")" ] && printf "ﱝ" && exit

vol=$(echo "$volstat" | awk -F[][] '/%/ {print $2;exit}' | awk -F% '{print $1}')

if [ "$vol" -gt "50" ]; then
    icon=""
elif [ "$vol" -lt "30" ]; then
    icon=""
else
    icon=""
fi

printf "%s %s%%" "$icon" "$vol"

# printf " | "
