#!/bin/bash

if [ "$(cat /sys/class/net/w*/operstate)" = 'down' ]; then
    wifistatus="睊"
else
    wifistatus=$(grep "^\s*w" /proc/net/wireless | awk '{ print " ", int($3 * 100 / 70) "%"  }')
    # download=" $(ifstat 0.1 1 | awk 'NR==3{printf("%.1f",$3/1000)}')MB/s"
    # upload=" $(ifstat 0.1 1 | awk 'NR==3{printf("%.1f",$4/1000)}')MB/s"
    # printf "%s %s " "$download" "$upload" 
fi

ethernet="$(cat /sys/class/net/e*/operstate | sed "s/down/ /;s/up/ /")"

connectivity=""
ping -c1 google.com > /dev/null 2>&1
if [ "$?" == 0 ]; then
    connectivity=""
fi

printf "%s%s%s" "$wifistatus" "$ethernet" " $connectivity"

printf " | "
