#!/bin/bash

word="$(dmenu -i -p "Enter word to look up in dictionary:" <&-)"

[ -z "$word" ] && exit 1

figlet "DICTIONARY" > /tmp/def
curl -s dict://dict.org/d:$word | sed '/^2/d' >> /tmp/def

! [ "$(grep '^151' /tmp/def)" ] && notify-send "No definition for '$word'" && exit 1

st -t "Definition of $word" -e less /tmp/def
