#!/bin/bash

# Status bar commands

delim="|"

dte() {
    echo "$(date +"%a %d. %b %H:%M")"
}

volume() {
    # echo "Vol: $(amixer -D pulse get Master | awk -F[][] '/%/ {print $2;exit}')"
    volstat="$(amixer -D pulse get Master)"

    echo "$volstat" | grep "\[off\]" >/dev/null && printf "🔇\n" && echo "$delim" && return

    vol=$(echo "$volstat" | awk -F[][] '/%/ {print $2;exit}' | awk -F% '{print $1}')

    if [ "$vol" -gt "70" ]; then
        icon="🔊"
    elif [ "$vol" -lt "30" ]; then
        icon="🔈"
    else
        icon="🔉"
    fi

    printf "%s %s%%\\n" "$icon" "$vol"
    echo "$delim"
}

wifi() {
    # echo "$(grep "^\s*w" /proc/net/wireless | awk '{print "WiFi:", int($3 * 100 / 70) "%"}')"
    [ "$(cat /sys/class/net/w*/operstate)" = 'down'  ] && wifiicon="📡"
    [ ! -n "${wifiicon+var}"  ] && wifiicon=$(grep "^\s*w" /proc/net/wireless | awk '{ print "📶", int($3 * 100 / 70) "%"  }')
    printf "%s %s\n" "$wifiicon" "$(cat /sys/class/net/e*/operstate | sed "s/down/❎/;s/up/🌐/")"
    echo "$delim"
}

memory() {
    mem=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')
    icon=""
    printf "%s %s" "$icon $mem"
    echo "$delim"
}

cpu_temp() {
    temp=$(sensors | awk '/Tdie/ {print $2}')
    icon=""
    printf "%s %s" "$icon $temp"
    echo "$delim"
}

dropbx() {
    if [[ "$(pgrep dropbox)" ]]; then
        echo ""
    else
        return
    fi
    dropbox status | grep "Sync" > /dev/null && echo "♻️"
    echo "$delim"
}

bluetooth() {
    [ "$(bluetoothctl info | awk '/Connected/ {print $2}')" = 'yes' ] && echo -e "\n$delim"
}

status() {
    bluetooth
    dropbx
    cpu_temp
    memory
    wifi
    volume
    dte
}

while true; do
    xsetroot -name " $(status | tr "\n" " ")"
    sleep 10
done &

