#!/bin/sh

if [ "$1" = "-k" ]; then
    echo "Shutting down Elasticsearch and Kibana..."
    screen -X -S elastic quit
    screen -X -S kibana quit
else 
    [ "$1" = -8 ] && version="8.10.3" || version="7.17.7"
    echo "Starting up Elasticsearch and Kibana..."
    screen -dmS elastic $HOME/elastic/elasticsearch-$version/bin/elasticsearch
    screen -dmS kibana $HOME/elastic/kibana-$version/bin/kibana
fi
screen -ls

