#!/bin/bash

sudo pacman -S git curl openssh picom xorg-xset xorg-server pkgconfig sxiv sxhkd xorg-xinit gvim sudo libnotify notification-daemon alsa-utils bluez bluez-utils pulseaudio-bluetooth fakeroot pavucontrol nitrogen networkmanager man-db man-pages playerctl bash-completion dmenu
