#!/bin/bash

packages="arandr bash-completion clipmenu clipnotify cmake docker docker-compose jq dmenu efibootmgr fakeroot figlet gcc git grub htop libnotify make man-db man-pages mlocate neofetch networkmanager nitrogen notification-daemon noto-fonts-emoji ntfs-3g ntp openssh os-prober pacman-contrib patch picom pkgconf python-pip qpdf scrot slock sudo sxhkd sxiv the_silver_searcher tldr ttf-joypixels ttf-ubuntu-font-family unzip xclip xdotool xorg-server xorg-xclipboard xorg-xinit xorg-xkill xorg-xsetroot zathura zathura-pdf-poppler x11-ssh-askpass xdotool yarn neovim"

desktoppackages="alsa-utils bluez bluez-utils discord imagemagick mpv pamixer pavucontrol playerctl pulseaudio-alsa pulseaudio-bluetooth thunderbird nextcloud-client"

virtualboxpackages="virtualbox-guest-iso xf86-video-vmware"

texpackages="texlive-core texlive-fontsextra texlive-latexextra texlive-pictures texlive-publishers texlive-science"

nvidiapackages="nvidia nvidia-settings"

read -p "Is this a proper desktop? (y/N) " desktop
[ "$desktop" == "y" ] && packages+=" $desktoppackages"

read -p "Install virtualbox guest packages? (y/N)" virtualbox
[ "$virtualbox" == "y" ] && packages+=" $virtualboxpackages"


read -p "Do you want to install tex-live packages? (y/N) " texlive
[ "$texlive" == "y" ] && packages+=" $texpackages"

read -p "Do you want to install nvidia packages? (y/N) " nvidia
[ "$nvidia" == "y" ] && packages+=" $nvidiapackages"


sudo pacman -Syu --needed $@ $packages
