#!/bin/bash

packages="alsa-utils base bash-completion bluez bluez-utils chntpw clipmenu clipnotify cmake discord dmenu efibootmgr fakeroot figlet gcc gendesk git graphviz grub gvim htop imagemagick libnotify linux linux-firmware make man-db man-pages mlocate mpv neofetch networkmanager nitrogen notification-daemon noto-fonts-emoji ntfs-3g ntp nvidia nvidia-settings openssh os-prober pacman-contrib pamixer patch pavucontrol picom pkgconf playerctl pulseaudio-alsa pulseaudio-bluetooth python-cairo python-gobject python-pip qpdf scrot slock sudo sxhkd sxiv the_silver_searcher thunderbird tldr ttf-joypixels ttf-ubuntu-font-family unzip xclip xdotool xorg-xclipboard xorg-xinit xorg-xkill xorg-xsetroot youtube-dl zathura zathura-pdf-poppler"

texpackages="texlive-core texlive-fontsextra texlive-latexextra texlive-pictures texlive-publishers texlive-science"

read -p "Do you want to install tex-live packages? (y/N) " texlive
[ "$texlive" == "y" ] && packages+=" $texpackages"

sudo pacman -Syu --needed $@ $packages
