#!/bin/bash

[ $# -lt 2 ] && echo "$# arguments given, at least 2 required (<pattern> <substitution> [path])" && exit 1

files="$(ag -l "$1" $3)"

[ -z "$files" ] && echo "Pattern '$1' has no match in $(pwd)" && exit

echo "The following matches of the pattern '$1' will be changed to '$2':"
ag "$1" $3
echo ""
read -p "Do you wish to proceed? (y/N) " answer
[ "$answer" != "y" ] && echo "Aborted.." && exit

perl -p -i -e "s/$1/$2/g" `ag -l "$1" $3` && echo "Success!"
