#!/bin/bash

sinkinput="$(pactl list short sinks | awk '{print $2}' | dmenu -i -p "Change default sink to which sink?" -l 5)"

[ -z "$sinkinput" ] || ( pactl set-default-sink $sinkinput && notify-send "Audio Playback" "Default sink changed to $sinkinput" )

