#!/bin/bash

output="$(nvidia-settings --query CurrentMetaMode)"

if [[ `echo "$output" | grep "ForceCompositionPipeline"` ]]; then
    setstate="Off"        
    output=`echo "$output" | sed 's/,[^,]*}/}/g'`
else
    setstate="On"
    output=`echo "$output" | sed 's/}/, ForceCompositionPipeline=On}/g'`
fi
    
output=`echo "$output" | sed 's/^.*:: //g'`
nvidia-settings --assign CurrentMetaMode="$output" && notify-send "NVIDIA Settings" "ForceCompositionPipeline set to $setstate"

