#!/bin/bash

# Remove DE
sudo apt-get purge lightdm* gdm3 xfce* gnome* xubuntu-desktop
sudo apt autoremove

# Install needed packages
sudo apt update
sudo apt install neovim vim git make gcc libx11-dev libxft-dev libxinerama-dev libx11-xcb-dev libxcb-res0-dev suckless-tools xorg sxhkd lm-sensors neofetch curl arandr zathura yarn nodejs mlocate apt-transport-https gnupg tldr silversearcher-ag

# Install Brave
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser

read -p "Are you using this Ubuntu machine inside virtualbox? [y/N]" vbans
[ $vbans == "y" ] && sudo apt install virtualbox-guest-utils virtualbox-guest-x11

# Clone dotfiles
git clone --bare https://github.com/shahzebs/dotfiles $HOME/.git-dotfiles
function config {
    /usr/bin/git --git-dir=$HOME/.git-dotfiles/ --work-tree=$HOME $@
}
mkdir -p $HOME/.dotfiles-backup
config checkout
if [ $? = 0 ]; then
    echo "Checked out dotfiles.";
else
    echo "Backing up pre-existing dot files.";
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | sed 's|\(\.*\w*/\).*$|\1|' | sort -u | xargs -I{} mv -f $HOME/{} $HOME/.dotfiles-backup/{}
fi
config checkout
config config status.showUntrackedFiles no 

# Cache fonts
fc-cache

# Link scripts
$HOME/.scripts/linkscripts

# Install vim-plug for nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# SSH key generation and git config
ssh-keygen
git config --global user.name "shahzebs"
git config --global user.email "shahzeb.syed96@gmail.com"
config remote set-url origin git@github.com:shahzebs/dotfiles.git

# Install dwm, st, dwmblocks and dmenu
cd $HOME/.suckless/dwm && make && sudo make install
cd $HOME/.suckless/dwmblocks && make && sudo make install
cd $HOME/.suckless/st && make && sudo make install
cd $HOME/.suckless/dmenu && make && sudo make install
echo "exec dwm" > $HOME/.xsession

echo -e "\nChange branch to ubuntu, reboot, log in and run \`startx\` to enter dwm"
