#!/bin/bash

function selectwifi {
    notify-send "WiFi Connection" "Looking for wireless connections"

    activewifi="$(nmcli device wifi list --rescan yes | grep '\*' | sed 's/\*//; /--/d; s/ *Infra.*$//g; s/^.*:\w\w  //g')"
    wifilist="$(nmcli device wifi list | tail -n +2 | sed 's/\*//; /--/d; s/ *Infra.*$//g; s/^.*:\w\w  //g')"
    
    [ -z "$wifilist" ] && wifilist="$(nmcli connection show | tail -n +2 | sed 's/  .*$//g')"

    selectedwifi="$(echo "$wifilist" | dmenu -i -l 10 -p "Current WiFi is $activewifi. Select WiFi:")"

    [ -z "$selectedwifi" ] && exit 1

    if [ -n "$(nmcli connection show | grep "$selectedwifi\s")" ]; then
        status="$(nmcli connection up "$selectedwifi")"
    else
        status=""
    fi

    while [[ $status != *"success"* ]]; do
        password="$(dmenu -i -p "Enter password for $selectedwifi or ':q' to return to selection:" <&-)"

        [ -z "$password" ] && exit 1
        
        [ "$password" == ":q" ] && selectwifi && return

        [ -n "$(nmcli connection show | grep "$selectedwifi\s")" ] && nmcli connection delete "$selectedwifi"

        status="$(nmcli device wifi connect "$selectedwifi" password "$password")"
    done
}

selectwifi

notify-send "WiFi Connection" "Wireless connection with $selectedwifi successful"



